### ISSUE TITLE
Cannot compile custom AutofacNancyBootstrapper with ScriptCs on Mac

### ISSUE THREAD

**Issue by c0ntinuum** [scriptcs/scriptcs-samples#24]
Apologies in advance if this is the wrong place for this "bug report" (please advise) I'm posting it here as I'm trying to get a sample of my own going going based on the scriptcs / autofac / nancyfx samples here... ;)

Cross posted to here: http://stackoverflow.com/questions/29276493/cannot-compile-custom-autofacnancybootstrapper-with-scriptcs-on-mac

I can't compile the following file `Bootstrapper.csx` on the latest ScriptCs (v0.14.0):

```C#
using Autofac;
using Nancy.Bootstrappers.Autofac;

public class Bootstrapper : AutofacNancyBootstrapper
{
    private readonly ILifetimeScope _lifetimeScope;

    public Bootstrapper(ILifetimeScope lifetimeScope)
    {
        _lifetimeScope = lifetimeScope;
    }

    protected override ILifetimeScope GetApplicationContainer()
    {
        return _lifetimeScope;
    }
}
```

It produces the following error:

```console
(15,39): error CS0508: `Bootstrapper.GetApplicationContainer()':
    return type must be `Autofac.ILifetimeScope' to match overridden member
    `Nancy.Bootstrappers.Autofac.AutofacNancyBootstrapper.GetApplicationContainer()'
/Users/tnt/Development/GitHub/scriptcs-gulp-nancyfx/scriptcs_packages
    /Nancy.Bootstrappers.Autofac.1.1/lib/net40/Nancy.Bootstrappers.Autofac.dll
   (Location of the symbol related to previous error)
```

My `scriptcs_packages.config` is as follows:

```XML
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Autofac" version="3.5.2" targetFramework="net40" />
  <package id="Nancy" version="1.1" targetFramework="net40" />
  <package id="Nancy.Bootstrappers.Autofac" version="1.1" targetFramework="net40" />
  <package id="Nancy.Hosting.Self" version="1.1" targetFramework="net40" />
</packages>
```

I have based the code from this example so I suspect it should work:

http://stackoverflow.com/questions/28559943/how-to-use-autofac-to-resolve-instance-per-request-dependencies-for-types-in-a-c

I apologise in advance if I am doing something really obvious wrong but I just can't see it...

Note: I don't have a Windows machine (on me) so I can't test it in Windows to see if it works there (but I will be able to do that tomorrow)...

**Comment by adamralph** [comment]
Hi @c0ntinuum, can you please reraise this over at https://github.com/scriptcs/scriptcs

**Comment by adamralph** [comment]
Actually, let's attempt to deal with this on SO first, and we'll see if an issue comes out of it.

**Comment by c0ntinuum** [comment]
:+1:
